<Project>
  <PropertyGroup>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <EnableWindowsTargeting Condition="'$(OS)' != 'Windows_NT'">true</EnableWindowsTargeting>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <None Remove="artifacts\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="artifacts\**\*" />
  </ItemGroup>
</Project>
