<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RootNamespace>SocketJackTests</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Controls" />
    <Import Include="System.Windows.Data" />
    <Import Include="System.Windows.Documents" />
    <Import Include="System.Windows.Input" />
    <Import Include="System.Windows.Media" />
    <Import Include="System.Windows.Media.Imaging" />
    <Import Include="System.Windows.Navigation" />
    <Import Include="System.Windows.Shapes" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="MonoTorrent" Version="3.0.2" />
    <PackageReference Include="MsgPack.Cli" Version="1.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="UI.SyntaxBox" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SocketJack.Windows\SocketJack.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TestControls\BandwidthTest.xaml.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="TestControls\Base\TestTemplate.xaml.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="TestControls\WebSocketTest.xaml.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="TestControls\HttpServerTest.xaml.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="TestControls\TorrentClientTest2.xaml.vb">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="if exist &quot;$(TargetPath).locked&quot; del &quot;$(TargetPath).locked&quot;" />
  </Target>

</Project>
