<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SocketJack.Windows\SocketJack.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ComputeSharp" Version="3.2.0" />
    <PackageReference Include="JackDebug.WPF" Version="1.4.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    <AssemblyTitle>Using SocketJack to make a basic game in WPF</AssemblyTitle>
    <Product>Using SocketJack to make a basic game in WPF</Product>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <StartupObject>SocketJack.WpfBasicGame.App</StartupObject>
  </PropertyGroup>

</Project>
