<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SocketChat</AssemblyName>
    <RootNamespace>SocketJack.SocketChat.Windows</RootNamespace>
    <AssemblyTitle>SocketChat</AssemblyTitle>
    <Product>SocketChat</Product>
    <StartupObject>SocketJack.SocketChat.Windows.App</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SocketJack.SocketChat\SocketJack.SocketChat.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
</Project>
