<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>False</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Audio\male.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Audio\male.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
